--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XPocketMC/ClearLagg
build-by-default: true
branches:
- main
projects: 
  ClearLagg:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
    icon: "OIG1-removebg-preview.png"
...
