--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XPocketMC/ClearLagg
build-by-default: true
branches:
- main
projects: 
  ClearLagg:
    path: ""
    icon: "OIG1-removebg-preview.png"
...
