--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XPocketMC/ClearLagg
build-by-default: true
branches:
- stable
- 1.1.0
- main
projects: 
  ClearLagg:
    path: ""
    libs:
      - src: NurAzli/UpdateNotifications/UpdateNotifications
        version: ^1.0.0
    icon: "OIG1-removebg-preview.png"
...
