name: ClearLagg
main: ClousClouds\ClearLagg\Main
version: 1.0.0 #for test update notify
api: 5.0.0
website: https://clouscloudsplugins.web.app
author: [AzliRynz, ClousCloud, NurAzli]
description: A plugin to reduce lag by clearing dropped items.
softdepend:
  - ScoreHud
commands:
  clearlagg:
    description: Clears all dropped items.
    permission: clearlagg.command
    aliases: [cl, lag, lagg]
permissions:
  clearlagg.command:
    default: op
    description: Allows the player to use the clearlagg command.
  clearlagg.stats.command:
    default: op
    description: Allows the player to view clearlagg statistics.
